import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, mkdir, readFile, readdir, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { artifactDigest, canonicalJson, parseJsonText, validateArtifactPath, validateManifest } from '../../spec/src/index.js';
import { packDirectory, resolveRequestPath } from '../../core/src/index.js';
import { readOciLayout, writeOciLayout } from '../../transport-oci/src/index.js';

// JSON files are the cross-language contract; this file only adapts operations to
// the JS reference. No expected bytes/digests are generated by production code.
const corpusRoot = new URL('../../../docs/conformance/v0.2/', import.meta.url);
const operations = ['blob', 'canonical', 'manifest', 'pack', 'parse', 'path', 'request'];
const categories = new Set([
  'OWA_INVALID_JSON', 'OWA_INVALID_JSON_VALUE', 'OWA_INVALID_MANIFEST',
  'OWA_UNSUPPORTED_SPEC_VERSION', 'OWA_UNSUPPORTED_ARTIFACT_TYPE',
  'OWA_INVALID_PATH', 'OWA_DUPLICATE_PATH', 'OWA_INVALID_DIGEST',
  'OWA_INVALID_SIZE', 'OWA_INVALID_MEDIA_TYPE', 'OWA_MISSING_ENTRYPOINT',
  'OWA_MISSING_SPA_FALLBACK', 'OWA_INVALID_VISIBILITY', 'OWA_INVALID_EXPIRY',
  'OWA_INVALID_ANNOTATIONS', 'OWA_SYMLINK', 'OWA_CONTENT_DIGEST_MISMATCH',
  'OWA_CONTENT_SIZE_MISMATCH'
]);
const corpusNames = (await readdir(corpusRoot)).filter(name => name.endsWith('.json')).sort();
const corpora = await Promise.all(corpusNames.map(async name => ({
  name,
  ...JSON.parse(await readFile(new URL(name, corpusRoot), 'utf8'))
})));

function independentDigest(bytes) {
  return `sha256:${createHash('sha256').update(bytes).digest('hex')}`;
}

function errorCategory(error) {
  // Syntax failures belong to the host JSON parser, which has no OWA .code.
  return error instanceof SyntaxError ? 'OWA_INVALID_JSON' : error?.code;
}

async function assertFailure(run, expectedCategory, label) {
  await assert.rejects(run, error => {
    assert.equal(errorCategory(error), expectedCategory, `${label}: stable error category`);
    return true;
  });
}

function assertIdentity(value, expected, digestKey = 'artifactDigest') {
  const actual = canonicalJson(value);
  assert.equal(actual, expected.canonicalJson, 'exact canonical string (no added newline)');
  assert.deepEqual(Buffer.from(actual, 'utf8'), Buffer.from(expected.canonicalJson, 'utf8'));
  assert.equal(artifactDigest(value), expected[digestKey], 'static canonical identity');
}

async function withTempDirectory(run) {
  const root = await mkdtemp(join(tmpdir(), 'owa-fixture-'));
  try {
    return await run(root);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

function relativeFixturePath(path) {
  assert.equal(typeof path, 'string');
  assert.ok(path.length > 0 && !path.startsWith('/') && !path.includes('\\') && !path.includes('\0'));
  assert.ok(path.split('/').every(part => part && part !== '.' && part !== '..'));
  return path;
}

function decodeBytes(contentBase64) {
  assert.equal(typeof contentBase64, 'string');
  const bytes = Buffer.from(contentBase64, 'base64');
  assert.equal(bytes.toString('base64'), contentBase64, 'fixture bytes use canonical base64');
  return bytes;
}

async function materializeFiles(root, files) {
  const seen = new Set();
  for (const file of files) {
    const path = relativeFixturePath(file.path);
    assert.ok(!seen.has(path), `duplicate fixture setup path: ${path}`);
    seen.add(path);
    const filename = join(root, path);
    await mkdir(dirname(filename), { recursive: true });
    await writeFile(filename, decodeBytes(file.contentBase64));
  }
}

function assertBlobs(actual, expected) {
  assert.equal(actual.size, expected.length, 'exact blob count');
  for (const blob of expected) {
    const bytes = decodeBytes(blob.contentBase64);
    assert.equal(independentDigest(bytes), blob.digest, 'independent content digest');
    assert.ok(actual.has(blob.digest), `missing blob ${blob.digest}`);
    assert.deepEqual(Buffer.from(actual.get(blob.digest)), bytes, 'exact blob bytes');
  }
}

async function runVector(operation, vector) {
  const expected = vector.expected;
  const input = Object.hasOwn(vector, 'inputJson') ? parseJsonText(vector.inputJson) : vector.input;
  switch (operation) {
    case 'canonical':
    case 'parse': {
      // Invoke even on a negative vector; assertIdentity is only for success.
      const actual = canonicalJson(input);
      if (!expected.errorCategory) {
        assert.equal(actual, expected.canonicalJson);
        assertIdentity(input, expected, 'digest');
      }
      return;
    }
    case 'manifest':
      validateManifest(input);
      if (!expected.errorCategory) assertIdentity(input, expected);
      return;
    case 'path': {
      const path = validateArtifactPath(input);
      if (!expected.errorCategory) assert.equal(path, expected.validatedPath);
      return;
    }
    case 'request': {
      validateManifest(input.manifest);
      const resolved = resolveRequestPath(input.manifest, input.urlPath);
      if (expected.resolvedPath === null) {
        assert.equal(resolved, null, 'invalid/unresolved requests return exactly null');
      } else {
        const file = input.manifest.files.find(item => item.path === expected.resolvedPath);
        assert.ok(file, 'expected path names an input manifest file');
        assert.deepEqual(resolved, file, 'resolver returns the exact matching file metadata');
      }
      return;
    }
    case 'pack':
      return withTempDirectory(async root => {
        await materializeFiles(root, input.files);
        for (const link of input.symlinks) {
          const filename = join(root, relativeFixturePath(link.path));
          relativeFixturePath(link.target);
          await mkdir(dirname(filename), { recursive: true });
          await symlink(link.target, filename, link.targetType === 'directory' ? 'dir' : 'file');
        }
        const packed = await packDirectory(root, input.entrypoint);
        if (!expected.errorCategory) {
          assert.deepEqual(packed.manifest, expected.manifest);
          assertIdentity(packed.manifest, expected);
          assert.equal(packed.artifactDigest, expected.artifactDigest);
          assert.deepEqual([...packed.blobs.keys()].sort(), expected.blobDigests);
          // Match returned blobs to independently hashed fixture source bytes.
          const source = new Map(input.files.map(file => {
            const bytes = decodeBytes(file.contentBase64);
            return [independentDigest(bytes), { digest: independentDigest(bytes), contentBase64: file.contentBase64 }];
          }));
          assertBlobs(packed.blobs, [...source.values()]);
        }
      });
    case 'blob':
      // All blob fixtures have valid metadata, including mismatched bytes/size.
      // Validation MUST NOT claim to verify file content; OCI is the boundary.
      assert.doesNotThrow(() => validateManifest(input.manifest));
      return withTempDirectory(async root => {
        let result;
        if (input.boundary === 'oci-write') {
          const blobs = new Map(input.blobs.map(blob => [blob.digest, decodeBytes(blob.contentBase64)]));
          result = await writeOciLayout({ manifest: input.manifest, blobs, output: root });
          if (!expected.errorCategory) {
            assert.equal(result.artifactDigest, expected.artifactDigest);
            result = await readOciLayout({ input: root });
          }
        } else {
          assert.equal(input.boundary, 'oci-read');
          await materializeFiles(root, input.layoutFiles);
          result = await readOciLayout({ input: root });
        }
        if (!expected.errorCategory) {
          assert.deepEqual(result.manifest, input.manifest);
          assertIdentity(result.manifest, expected);
          assert.equal(result.artifactDigest, expected.artifactDigest);
          assertBlobs(result.blobs, expected.blobs);
        }
      });
    default:
      assert.fail(`Unsupported fixture operation: ${operation}`);
  }
}

test('portable corpus structure and independent static digest goldens', () => {
  assert.deepEqual(corpusNames, operations.map(operation => `${operation}.json`));
  const ids = new Set();
  for (const corpus of corpora) {
    assert.equal(corpus.format, 'owa-conformance-v1');
    assert.equal(corpus.specVersion, 'owa.dev/v1');
    assert.equal(corpus.name, `${corpus.operation}.json`);
    assert.ok(Array.isArray(corpus.notes) && corpus.notes.length > 0);
    assert.ok(Array.isArray(corpus.vectors) && corpus.vectors.length > 0);
    for (const vector of corpus.vectors) {
      assert.equal(typeof vector.id, 'string');
      assert.ok(vector.id.startsWith(`${corpus.operation}-`));
      assert.ok(!ids.has(vector.id), `duplicate vector ID: ${vector.id}`);
      ids.add(vector.id);
      assert.equal(typeof vector.description, 'string');
      assert.notEqual(Object.hasOwn(vector, 'input'), Object.hasOwn(vector, 'inputJson'));
      if (Object.hasOwn(vector, 'inputJson')) assert.equal(typeof vector.inputJson, 'string');
      if (vector.expected.errorCategory) {
        assert.ok(categories.has(vector.expected.errorCategory), vector.expected.errorCategory);
        assert.deepEqual(Object.keys(vector.expected), ['errorCategory']);
      } else if (['canonical', 'manifest', 'parse', 'pack', 'blob'].includes(corpus.operation)) {
        assert.equal(typeof vector.expected.canonicalJson, 'string');
        const key = ['canonical', 'parse'].includes(corpus.operation) ? 'digest' : 'artifactDigest';
        assert.equal(independentDigest(Buffer.from(vector.expected.canonicalJson, 'utf8')), vector.expected[key], vector.id);
        if (vector.expected.manifest) assert.deepEqual(JSON.parse(vector.expected.canonicalJson), vector.expected.manifest);
      } else if (corpus.operation === 'path') {
        assert.equal(vector.expected.validatedPath, vector.input);
      } else if (corpus.operation === 'request') {
        assert.ok(vector.expected.resolvedPath === null || typeof vector.expected.resolvedPath === 'string');
      }
    }
  }
});

for (const corpus of corpora) {
  for (const vector of corpus.vectors) {
    test(`${corpus.operation}: ${vector.id} — ${vector.description}`, async () => {
      if (vector.expected.errorCategory) {
        await assertFailure(() => runVector(corpus.operation, vector), vector.expected.errorCategory, vector.id);
      } else {
        await runVector(corpus.operation, vector);
      }
    });
  }
}

test('published legacy files are byte-for-byte immutable (independent pinned SHA-256)', async () => {
  // Computed from latest main before corpus changes, using Python hashlib.
  // Do not regenerate these pins or any JSON goldens from production at test time.
  const pins = {
    'artifact-digest.txt': 'sha256:49d95b7b03b2eb1f367801d95c17a847a0b335653df0a7562ac3b09e537e5925',
    'canonical.json': 'sha256:388a9912105ef49dab9d867b44c98f2c0cb2954139580bf56314b6818c206253',
    'index.html': 'sha256:f6c64c97726aac94c47f997a6875c727f8a889043393bd398fe008e3edeb63b0',
    'manifest.json': 'sha256:af31c7e942204c39a19fa04ff39976bf349328d1595c6bc680b8b7ab7c06bf29'
  };
  const legacyRoot = new URL('../../../docs/test-vectors/basic/', import.meta.url);
  for (const [name, digest] of Object.entries(pins)) {
    assert.equal(independentDigest(await readFile(new URL(name, legacyRoot))), digest, name);
  }
});

test('fixture runner rejects wrong categories and unexpected success', async () => {
  // Guard the harness itself: negative fixtures may not pass just because any
  // exception happened (e.g. assertion errors or filesystem setup failures).
  assert.equal(errorCategory(new SyntaxError('host parser')), 'OWA_INVALID_JSON');
  assert.equal(errorCategory(Object.assign(new Error('irrelevant text'), { code: 'OWA_INVALID_PATH' })), 'OWA_INVALID_PATH');
  assert.equal(errorCategory(new Error('OWA_INVALID_PATH')), undefined);
  assert.equal(errorCategory(Object.assign(new Error(), { code: 'OTHER' })), 'OTHER');
  await assertFailure(async () => { throw new SyntaxError('host parser'); }, 'OWA_INVALID_JSON', 'parser mapping');
  await assertFailure(async () => { throw Object.assign(new Error('arbitrary wording'), { code: 'OWA_INVALID_PATH' }); }, 'OWA_INVALID_PATH', 'correct category');
  for (const wrongError of [new Error('OWA_INVALID_PATH'), Object.assign(new Error(), { code: 'OTHER' }), new SyntaxError('wrong operation')]) {
    await assert.rejects(() => assertFailure(async () => { throw wrongError; }, 'OWA_INVALID_PATH', 'wrong category'), { code: 'ERR_ASSERTION' });
  }
  await assert.rejects(() => assertFailure(async () => {}, 'OWA_INVALID_PATH', 'unexpected success'), { code: 'ERR_ASSERTION' });
});
