import { createHmac, timingSafeEqual } from 'node:crypto';
import { isIP } from 'node:net';
import { TextDecoder } from 'node:util';

export const CAPABILITIES = Object.freeze(['plan', 'upload', 'commit', 'activate', 'read']);

const ERRORS = Object.freeze({
  OWA_AUTH_CONFIG: [500, 'Invalid authentication configuration'],
  OWA_AUTH_INVALID_TOKEN: [401, 'Invalid authentication token'],
  OWA_AUTH_INVALID_SIGNATURE: [401, 'Invalid authentication signature'],
  OWA_AUTH_EXPIRED: [401, 'Authentication token expired'],
  OWA_AUTH_MISSING: [401, 'Authentication required'],
  OWA_AUTH_SITE: [403, 'Authentication does not permit this site'],
  OWA_AUTH_CAPABILITY: [403, 'Authentication does not permit this operation'],
  OWA_AUTH_DEV_ONLY: [403, 'Development authentication requires a direct loopback connection']
});
const MAX_TOKEN_LENGTH = 8192;
const CLAIM_KEYS = ['v', 'jti', 'exp', 'sites', 'capabilities'];

// Only fixed messages are accepted; errors never carry tokens, secrets, or causes.
export class AuthError extends Error {
  constructor(code) {
    const safeCode = Object.hasOwn(ERRORS, code) ? code : 'OWA_AUTH_CONFIG';
    const [status, message] = ERRORS[safeCode];
    super(message);
    this.name = 'AuthError';
    this.code = safeCode;
    this.status = status;
  }
}

export function isSiteScope(site) {
  return typeof site === 'string' && /^[a-z0-9][a-z0-9_-]{0,62}(?![\s\S])/.test(site);
}

// Inspect actual socket addresses only, never Host or forwarding headers.
export function isLoopback(address) {
  if (typeof address !== 'string') return false;
  if (address === '::1') return true;
  if (isIP(address) === 4) return address.startsWith('127.');
  if (/^::ffff:/i.test(address)) {
    const ipv4 = address.slice(7);
    return isIP(ipv4) === 4 && ipv4.startsWith('127.');
  }
  return false;
}

function secretBytes(secret) {
  // Strings are UTF-8; Buffers are raw bytes. Copy Buffers to prevent later
  // mutation of the caller's configuration from changing a running authorizer.
  if (typeof secret !== 'string' && !Buffer.isBuffer(secret)) throw new AuthError('OWA_AUTH_CONFIG');
  const bytes = Buffer.from(secret, 'utf8');
  if (bytes.length < 32) throw new AuthError('OWA_AUTH_CONFIG');
  return bytes;
}

function makeClock(now = () => Math.floor(Date.now() / 1000)) {
  if (typeof now !== 'function') throw new AuthError('OWA_AUTH_CONFIG');
  return () => {
    let seconds;
    try { seconds = now(); } catch { throw new AuthError('OWA_AUTH_CONFIG'); }
    if (!Number.isSafeInteger(seconds) || seconds < 0) throw new AuthError('OWA_AUTH_CONFIG');
    return seconds;
  };
}

function checkOptions(options) {
  if (!options || typeof options !== 'object' || Array.isArray(options)) throw new AuthError('OWA_AUTH_CONFIG');
}

function sortedUnique(values, max, valid) {
  if (!Array.isArray(values) || values.length < 1 || values.length > max) throw new AuthError('OWA_AUTH_INVALID_TOKEN');
  // Array.from also exposes holes as undefined rather than skipping them.
  const copy = Array.from(values);
  if (!copy.every(valid) || new Set(copy).size !== copy.length) throw new AuthError('OWA_AUTH_INVALID_TOKEN');
  return copy.sort();
}

function validatedClaims(value) {
  if (!value || typeof value !== 'object' || Array.isArray(value)
    || Object.keys(value).length !== CLAIM_KEYS.length
    || !CLAIM_KEYS.every(key => Object.hasOwn(value, key))
    || value.v !== 1
    || typeof value.jti !== 'string' || !/^[A-Za-z0-9_-]{1,128}(?![\s\S])/.test(value.jti)
    || !Number.isSafeInteger(value.exp) || value.exp <= 0) throw new AuthError('OWA_AUTH_INVALID_TOKEN');
  return {
    v: 1,
    jti: value.jti,
    exp: value.exp,
    sites: sortedUnique(value.sites, 64, isSiteScope),
    capabilities: sortedUnique(value.capabilities, CAPABILITIES.length, cap => CAPABILITIES.includes(cap))
  };
}

function sign(payload, key) {
  return createHmac('sha256', key).update(`owa1.${payload}`, 'ascii').digest();
}

function decodeSegment(segment) {
  if (!/^[A-Za-z0-9_-]+(?![\s\S])/.test(segment)) throw new AuthError('OWA_AUTH_INVALID_TOKEN');
  const bytes = Buffer.from(segment, 'base64url');
  if (bytes.toString('base64url') !== segment) throw new AuthError('OWA_AUTH_INVALID_TOKEN');
  return bytes;
}

/**
 * Mint an owa1 token. secret is a >=32-byte Buffer or UTF-8 string; now, if
 * supplied, is a callback returning nonnegative safe-integer Unix seconds.
 * jti is an explicit operator-supplied audit identifier, never autogenerated.
 * Token JSON has its own fixed field order; artifact canonicalization is not used.
 */
export function createToken(options = {}) {
  checkOptions(options);
  const key = secretBytes(options.secret);
  const now = makeClock(options.now)();
  const claims = validatedClaims({ v: 1, jti: options.jti, exp: options.exp, sites: options.sites, capabilities: options.capabilities });
  if (claims.exp <= now) throw new AuthError('OWA_AUTH_EXPIRED');
  const payload = Buffer.from(JSON.stringify(claims), 'utf8').toString('base64url');
  const token = `owa1.${payload}.${sign(payload, key).toString('base64url')}`;
  if (token.length > MAX_TOKEN_LENGTH) throw new AuthError('OWA_AUTH_INVALID_TOKEN');
  return token;
}

function verifyWithKey(token, key, now) {
  if (typeof token !== 'string' || token.length > MAX_TOKEN_LENGTH) throw new AuthError('OWA_AUTH_INVALID_TOKEN');
  const parts = token.split('.');
  if (parts.length !== 3 || parts[0] !== 'owa1') throw new AuthError('OWA_AUTH_INVALID_TOKEN');
  const payload = decodeSegment(parts[1]);
  const signature = decodeSegment(parts[2]);
  if (signature.length !== 32) throw new AuthError('OWA_AUTH_INVALID_TOKEN');
  // Both arguments are exactly 32 bytes. Authenticate before parsing claims.
  if (!timingSafeEqual(signature, sign(parts[1], key))) throw new AuthError('OWA_AUTH_INVALID_SIGNATURE');
  let parsed;
  try {
    // Preserve a BOM so it cannot be silently stripped before the byte comparison.
    const text = new TextDecoder('utf-8', { fatal: true, ignoreBOM: true }).decode(payload);
    parsed = JSON.parse(text);
  } catch { throw new AuthError('OWA_AUTH_INVALID_TOKEN'); }
  const claims = validatedClaims(parsed);
  // Reject unknown/duplicate members, ordering, whitespace, noncanonical numeric
  // or string spellings, and unsorted arrays even when a valid MAC is supplied.
  if (!Buffer.from(JSON.stringify(claims), 'utf8').equals(payload)) throw new AuthError('OWA_AUTH_INVALID_TOKEN');
  if (claims.exp <= now) throw new AuthError('OWA_AUTH_EXPIRED');
  return claims;
}

/** Verify and return only {v, jti, exp, sites, capabilities}, never token/key data. */
export function verifyToken(token, options = {}) {
  checkOptions(options);
  return verifyWithKey(token, secretBytes(options.secret), makeClock(options.now)());
}

function headerEntries(req, name) {
  return Object.entries(req?.headers ?? {}).filter(([key]) => key.toLowerCase() === name);
}

function rawHeaderCount(req, name) {
  if (req?.rawHeaders === undefined) return 0;
  if (!Array.isArray(req.rawHeaders) || req.rawHeaders.length % 2 !== 0) throw new AuthError('OWA_AUTH_INVALID_TOKEN');
  let count = 0;
  for (let i = 0; i < req.rawHeaders.length; i += 2) {
    if (typeof req.rawHeaders[i] !== 'string') throw new AuthError('OWA_AUTH_INVALID_TOKEN');
    if (req.rawHeaders[i].toLowerCase() === name) count++;
  }
  return count;
}

function bearerToken(req) {
  const entries = headerEntries(req, 'authorization');
  if (entries.length > 1 || rawHeaderCount(req, 'authorization') > 1) throw new AuthError('OWA_AUTH_INVALID_TOKEN');
  if (entries.length === 0) throw new AuthError('OWA_AUTH_MISSING');
  const value = entries[0][1];
  if (typeof value !== 'string' || value.length > MAX_TOKEN_LENGTH + 7) throw new AuthError('OWA_AUTH_INVALID_TOKEN');
  const match = /^Bearer ([^\s,]+)(?![\s\S])/i.exec(value);
  if (!match) throw new AuthError('OWA_AUTH_INVALID_TOKEN');
  return match[1];
}

/**
 * No environment is read here. mode defaults to required, with a prevalidated
 * secret. Explicit dev mode is ONLY for direct local development: deployers must
 * not expose it through a proxy (even a local proxy can strip forwarded headers).
 * now is a validated clock callback. authorize returns claims, or null in dev.
 */
export function createAuthorizer(options = {}) {
  checkOptions(options);
  const mode = options.mode === undefined ? 'required' : options.mode;
  if (mode !== 'required' && mode !== 'dev') throw new AuthError('OWA_AUTH_CONFIG');
  const key = mode === 'required' ? secretBytes(options.secret) : null;
  const now = makeClock(options.now);
  now(); // Reject invalid clocks at construction as well as at request time.
  return Object.freeze({
    mode,
    now,
    authorize(req, site, requiredCaps = []) {
      const seconds = now();
      if (!Array.isArray(requiredCaps) || !Array.from(requiredCaps).every(cap => CAPABILITIES.includes(cap))) throw new AuthError('OWA_AUTH_CONFIG');
      if (mode === 'dev') {
        if (!isLoopback(req?.socket?.remoteAddress)
          || headerEntries(req, 'forwarded').length > 0
          || Object.keys(req?.headers ?? {}).some(name => name.toLowerCase().startsWith('x-forwarded-'))
          || rawHeaderCount(req, 'forwarded') > 0 || rawHeaderCount(req, 'x-forwarded-for') > 0
          || (req?.rawHeaders ?? []).some((name, index) => index % 2 === 0 && name.toLowerCase().startsWith('x-forwarded-'))) throw new AuthError('OWA_AUTH_DEV_ONLY');
        if (!isSiteScope(site)) throw new AuthError('OWA_AUTH_SITE');
        return null;
      }
      const claims = verifyWithKey(bearerToken(req), key, seconds);
      if (!isSiteScope(site) || !claims.sites.includes(site)) throw new AuthError('OWA_AUTH_SITE');
      if (!requiredCaps.every(cap => claims.capabilities.includes(cap))) throw new AuthError('OWA_AUTH_CAPABILITY');
      return claims;
    }
  });
}
